#import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

Data=pd.read_csv('energy.csv')
#print(Data.Code.unique())
POL=Data.loc[Data.Code=='POL'].set_index('Year').select_dtypes(include='number')
FRA=Data.loc[Data.Code=='FRA'].set_index('Year').select_dtypes(include='number')
JPN=Data.loc[Data.Code=='JPN'].set_index('Year').select_dtypes(include='number')
ITA=Data.loc[Data.Code=='ITA'].set_index('Year').select_dtypes(include='number')
GBR=Data.loc[Data.Code=='GBR'].set_index('Year').select_dtypes(include='number')
USA=Data.loc[Data.Code=='USA'].set_index('Year').select_dtypes(include='number')
CAN=Data.loc[Data.Code=='CAN'].set_index('Year').select_dtypes(include='number')
CHN=Data.loc[Data.Code=='CHN'].set_index('Year').select_dtypes(include='number')
UKR=Data.loc[Data.Code=='UKR'].set_index('Year').select_dtypes(include='number')
plt.plot(POL,label="Polska")
plt.plot(FRA,label="Francja")
plt.plot(JPN,label="Japonia")
plt.plot(ITA,label="Włochy")
plt.plot(GBR,label="Wielka Brytania")
plt.plot(USA,label="USA")
plt.plot(CAN,label="Kanada")
plt.plot(CHN,label="Chiny")
plt.plot(UKR,label="Ukraina")
plt.legend(loc="upper left")
plt.xlabel("Lata")
plt.ylabel("Zużycie prądu per capita (kWh)")
plt.title("Zużycie prądu per capita dla grupy G7 + Polski + Ukrainy")
plt.show()